version: '3'

services:
  db:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=testpass
  web:
    build: .
    command: gunicorn --reload mozio_api.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
