version: '3'

services:
  db:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=testpass
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db